### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by applemuncy** [rubencarneiro/ubuntu_hammerhead_device_rootfs#1]
I'm getting a build error and it is possibly because I have not incorporated this repository in mu build setup. 
Perhaps the target path should be ubuntu/hammerhead/device/rootfs ?

I can't see where it would hurt to try that while waiting for your advice.

My build error was: 
`Target buildinfo: /home/apple/phablet/out/target/product/hammerhead/system/build.prop
/bin/bash: hammerhead: command not found
build/core/Makefile:217: recipe for target '/home/apple/phablet/out/target/product/hammerhead/system/build.prop' failed
make: *** [/home/apple/phablet/out/target/product/hammerhead/system/build.prop] Error 127
make: *** Deleting file '/home/apple/phablet/out/target/product/hammerhead/system/build.prop

**Comment by rubencarneiro** [comment]
Im at work now, i will look at when i reach home.

Em 08/11/2016 13:56, "apple muncy" <notifications@github.com> escreveu:

**Comment by rubencarneiro** [comment]
I found delete space PRODUCT_NAME= hammerhead to PRODUCT_NAME=hammerhead
In cm.mk

Em 08/11/2016 15:58, "Ruben Carneiro" <rubencarneiro01@gmail.com> escreveu:

**Comment by applemuncy** [comment]
`I found delete space PRODUCT_NAME= hammerhead to PRODUCT_NAME=hammerhead In cm.mk `

This is a problem? 

And I'm still not knowing how to use `ubuntu_hammerhead_device_rootfs`

**Comment by rubencarneiro** [comment]
Dont use that for nos lateral i explain to you how to use that

Em 08/11/2016 18:44, "apple muncy" <notifications@github.com> escreveu:

**Comment by rubencarneiro** [comment]
Dont use that, that is for use with ubuntu rootfs

Em 08/11/2016 18:45, "Ruben Carneiro" <rubencarneiro01@gmail.com> escreveu:

**Comment by applemuncy** [comment]
It gets added to vivid-preinstalled-touch-armhf.tar.gz    ?

**Comment by rubencarneiro** [comment]
No copy to inside the vivid-preinstalled-touch-armhf.tar.gz

**Comment by rubencarneiro** [comment]
Yes

Em 08/11/2016 18:49, "apple muncy" <notifications@github.com> escreveu:
